[project]
name = "hwp2pdf-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.13",
    "python-multipart>=0.0.20",
    "pywin32>=310",
    "uvicorn>=0.34.3",
]
